### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by atulvermaPRFT** [bschinina-twilio/flex-plugin-cold-transfer-workflow#1]
Hello,

Thank you for creating this feature. I was using the old version that uses task router event callback URL. 
This one uses the plugin to handle transfers but I am testing it and it is not working. I can see all logs executes in success but the call from Flex UI never gets transferred. Do you know if this feature has been tested? please provide some guidance.

Thank you
Atul

**Comment by brypo** [comment]
Hi Atul,

Thanks for filing this issue. There were two problems with the code (one a small typo, the other a method that was behaving in an undesired way). Both of these have been resolved, and the README has been improved. 

Please let me know if it's still giving you problems.

Best wishes,
B

**Comment by atulvermaPRFT** [comment]
Hi,

Thank you for your reply. I tested with the new code still not working. In the code, I found reducers are not defined. So I am importing from import reducers, { namespace } from './states'; I am not sure if that is the right way to do it.

The actual issue is when I run this plugin locally and initiate the cold transfer the task stays with the agent and ever gets into the queue.

Thanks
Atul

**Comment by brypo** [comment]
You are right - I was missing the import. In the future, I will update this repo to add the whole Plugin structure rather than just pulling out the main file. That might help make this easier to set up. Thanks for sharing this feedback.

If you are still getting an error, can you take a look at the console logs and share any errors you are getting (specifically when you click to transfer the task)?

**Comment by atulvermaPRFT** [comment]
Hello, and thank you for the update. I believe this action is missing in the plugin where await fetch(transferCustomerCallFunctionUrl, httpOpts). To complete the task transfer, it must execute await original(payload);.

There are currently no errors in the logs, but the transfer action is not getting complete.

Thanks
Atul
